### ISSUE TITLE
The latest update fails 

### ISSUE THREAD

**Issue by rickytower** [flathub/org.freedesktop.Sdk.Extension.texlive#84] opened 2022-04-21 09:25 UTC
Operating system: Fedora Silverblue 35
Flatpak version: 1.12.7

The latest update gives me this message (through the terminal):
`Warning: While pulling runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08 from remote flathub: Server returned HTTP 404`

**Comment by Juno42** [comment] 2022-04-21 17:33
OS: Pop!_OS 21.10

The Pop! Shop update includes the org.freedesktop.Sdk.Extension.texlive component, but can't seem to install it. Clicking "update" just spins the wheel a second before reverting back to update.

**Comment by fedelibre** [comment] 2022-04-21 19:26
I confirm there is probably a problem on flathub server.
Yesterday I launched a build of an app that requires this extension and the build is failing with this error:

```
FB: Using Flatpak version 1.13.2
FB: Running 'flatpak --user update --subpath= -y --noninteractive org.kde.Sdk/x86_64/5.15-21.08' on host
Updating runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
Warning: Failed to update org.freedesktop.Sdk.Extension.texlive: runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08 is not available
FB: host_command_exited_cb 72479 0
```

I can build that app locally because I installed texlive successfully a few weeks ago:

```
$ flatpak info org.freedesktop.Sdk.Extension.texlive

TeX Live Sdk extension - LaTeX packages and tools

          ID: org.freedesktop.Sdk.Extension.texlive
         Ref: runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
        Arch: x86_64
      Branch: 21.08
     Version: 20210325
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 7.7 GB

      Commit: 0a1c67eb57ac39bb9b3149f28907050fae360e63afcf01dbfb2ede69507a1098
      Parent: 11bcb635c9ac80b9fa471bd7f972199b422ffa0804f8f5949c65167b87adb9cd
     Subject: Update ghostscript-9.56.0.tar.xz to 9.56.1 (#78) (7b1b1e06)
        Date: 2022-04-06 02:02:29 +0000
```

**Comment by fedelibre** [comment] 2022-04-21 19:38
I see now the recent commit which upgraded texlive to version 2022. The build in #80 completed successfully... I hope someone can explain what's the problem.

**Comment by sstendahl** [comment] 2022-04-22 06:50
I've had the exact same issue on machine (Fedora Silverblue 36), started a bit less than a week ago if I recall correctly. 

Your mileage may vary, but I found that just removing this flatpak, and then installing again worked fine without issues. Just updating from the existing version spat out this 404 error, reinstalling completely worked for me.

**Comment by fedelibre** [comment] 2022-04-22 11:40
> I found that just removing this flatpak, and then installing again worked fine without issues

The problem for me is that it seems that the build in a PR updating an existing app does not install a dependency from scratch but it updates it. So there's no work around for my use case.

**Comment by hfiguiere** [comment] 2022-04-22 13:45
@barthalion any idea?

**Comment by barthalion** [comment] 2022-04-25 07:02
I assume it's the same problem that happens when installing debug extension for KDE runtime/SDK. I haven't looked into that yet.

**Comment by junefish** [comment] 2022-04-26 04:58
I've been having an issue updating this flatpak for a week or so.  Today I tried un- and re-installing as @SjoerdB93 suggested and it worked.  (Collapsed some of the output to not take over the comments with a giant wall of text.)

<pre>$ flatpak update
Looking for updates…


<b>        ID                                    Branch Op Remote  Download</b>
 1. [✗] org.freedesktop.Sdk.Extension.texlive 21.08  u  flathub 1.0 kB / 5.0 GB

Warning: runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08 is not available
Updates complete.
</pre>

<details><summary><code>$ flatpak remove org.freedesktop.Sdk.Extension.texlive</code></summary>
<pre>Similar installed refs found for ‘org.freedesktop.Sdk.Extension.texlive’:

   1) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/20.08 (system)
   2) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08 (user)
   3) All of the above

Which do you want to use (0 to abort)? [0-3]: 3

<b>        ID                                            Branch         Op</b>
 1. [<font color="#4E9A06">-</font>] org.freedesktop.Sdk.Extension.texlive         20.08          r

Uninstall complete.

<b>        ID                                            Branch         Op</b>
 1. [<font color="#4E9A06">-</font>] org.freedesktop.Sdk.Extension.texlive         21.08          r

Uninstall complete.</pre></details>

<details><summary><code>$ flatpak install org.freedesktop.Sdk.Extension.texlive</code></summary>
<pre>Looking for matches…
Remotes found with refs similar to ‘org.freedesktop.Sdk.Extension.texlive’:

   1) ‘flathub’ (system)
   2) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-2]: 1
Similar refs found for ‘org.freedesktop.Sdk.Extension.texlive’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
   2) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/18.08
   3) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/19.08
   4) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/20.08

Which do you want to use (0 to abort)? [0-4]: 1


<b>        ID                                    Branch Op Remote  Download</b>
 1. [<font color="#4E9A06">✓</font>] org.freedesktop.Sdk.Extension.texlive 21.08  i  flathub 4.6 GB / 5.0 GB

Installation complete.</pre></details>

<pre>$ flatpak update
Looking for updates…


<b>        ID                                    Branch Op Remote  Download</b>
 1. [<font color="#4E9A06">✓</font>] org.freedesktop.Sdk.Extension.texlive 21.08  i  flathub 4.6 GB / 5.0 GB

Installation complete.

$ flatpak update
Looking for updates…
Nothing to do.
</pre>

**Comment by sstendahl** [comment] 2022-04-26 07:29
@junefish Thanks for confirming that this indeed works for you too. I was initially a bit hesitant reporting my findings, because you would be left without a working version at all if it didn't work. (When I tried it initially myself, I thought the new install would perhaps give me this 404 error). I don't really want to be responsible for people bricking their setup of course :)

Decided to share my findings anyway because it could potentially help people out, and also maybe identify the problem. (After all, re-installing is more of a work-around than a fix)

**Comment by junefish** [comment] 2022-04-27 02:08
@SjoerdB93 yeah, absolutely.  I have my files backed up and Linux is easy enough to reinstall so I was willing to take that risk.

Happy to provide any logs or anything else that might be helpful for determining root cause.

**Comment by fedelibre** [comment] 2022-05-01 20:53
Today I managed to *update* my local installation. The latest commit 5 days ago simply updated a dependency...
However, the [build of the app](https://flathub.org/builds/#/builders/28/builds/10694) I maintain is still failing with this error:

```
Dependency Extension: org.freedesktop.Sdk.Extension.texlive 21.08
FB: Running 'flatpak --user info org.freedesktop.Sdk.Extension.texlive/x86_64/21.08 --show-commit' on host
FB: host_command_exited_cb 2557499 0
Updating org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
FB: Running 'flatpak --user update --subpath= -y --noninteractive org.freedesktop.Sdk.Extension.texlive/x86_64/21.08' on host
Updating runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
Error: Failed to update org.freedesktop.Sdk.Extension.texlive: While trying to checkout 18dda5730f94b360c6c7ee9aa06f8f2a907fd753c0adea1e6bd58aba6a183cad into /srv/buildbot/.local/share/flatpak/runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08/.18dda5730f94b360c6c7ee9aa06f8f2a907fd753c0adea1e6bd58aba6a183cad-50H7K1: Opening content object 24aa52473b97cd324d82d454173c7392a791ebe14cc7b36e763fd494c473434e: Couldn't find file object '24aa52473b97cd324d82d454173c7392a791ebe14cc7b36e763fd494c473434e'
FB: host_command_exited_cb 2557502 256
```

**Comment by fedelibre** [comment] 2022-05-02 16:52
Look at the [latest build](https://github.com/flathub/org.frescobaldi.Frescobaldi/pull/6#issuecomment-1114338592).
The aarch64 build installs texlive successfully, but then fails for another reason. The x86_64 build fails immediately because of texlive.

A problem with x86_64 arch?
But my laptop has x86_64 and updated successfully. I'm confused.

**Comment by fedelibre** [comment] 2022-09-21 08:19
Yesterday I launched a [new build of org.frescobaldi.Frescobaldi](https://github.com/flathub/org.frescobaldi.Frescobaldi/pull/12) and I'm having the same issue.

I'm wondering if the branch name in git may cause the problem. This extension is using an unusual name, that is `branch/21.08` instead of just `21.08`.

**Comment by hfiguiere** [comment] 2022-09-21 12:16
`branch/21.08`  is the git branch name for `21.08` branch. It's all fine.

**Comment by barthalion** [comment] 2022-09-21 12:27
This is a different problem this time – just a slow network or whatever, instead of some silent delta corruption.

**Comment by barthalion** [comment] 2022-09-21 13:30
As the build has passed, I'm going to close this issue. It doesn't seem to be an often occuring problem.

**Closed as completed by barthalion** 2022-09-21 13:30 UTC
